language: java

addons:
  sonarcloud:
    organization: "edmilsonverona-github"
  token:
      secure: 9200bf4162c4f941b05cb192431bffe6325e301a

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
